import type {LINK} from '@/types/onstord';

export const baseUrl =
  process.env.NODE_ENV === 'development'
    ? 'http://localhost:8080'
    : 'https://onstord-api.vercel.app';

export const Services: Array<LINK> = [
  {text: '1 on 1 Coaching', path: '#'},
  {text: 'Company Review', path: '#'},
  {text: 'Accounts Review', path: '#'},
  {text: 'HR Consulting', path: '#'},
  {text: 'SEO Optimisation', path: '#'}
];

export const Company: Array<LINK> = [
  {text: 'About', path: '#'},
  {text: 'Meet the Team', path: '#'},
  {text: 'Accounts Review', path: '#'}
];

export const HelpfulLinks: Array<LINK> = [
  {text: 'Contact', path: '#'},
  {text: 'FAQs', path: '#'},
  {text: 'Live Chat', path: '#'}
];

export const Legal: Array<LINK> = [
  {text: 'Accessibility', path: '#'},
  {text: 'Refund Policy', path: '#'},
  {text: 'Hiring Statistics', path: '#'}
];

export const Downloads: Array<LINK> = [
  {text: 'Marketing Calendar', path: '#'},
  {text: 'SEO Infographics', path: '#'}
];

export const initFormDetails = {
  firstName: '',
  lastName: '',
  title: 'Mr',
  email: '',
  phoneNumber: '',
  institutions: '',
  password: '',
  confirmPassword: ''
};

export const categories = [
  'Administration',
  'Agriculture',
  'Engineering, Environment & Technology',
  'Education',
  'Arts & Humanities',
  'Law',
  'Medical, Pharmaceutical & Health Sciences',
  'Sciences',
  'Social Sciences',
  'Management Sciences',
  'Mathematics and Statistics'
];

export const allUni = [
  'Abubakar Tafawa Balewa University, Bauchi',
  'Ahmadu Bello University, Zaria',
  'Bayero University Kano',
  'Federal University Birnin Kebbi',
  'Federal University Dutse, Jigawa State',
  'Federal University Dutsin-Ma, Katsina',
  'Federal University Gasua',
  'Federal University Kashere, Gombe State',
  'Federal University Lafia, Nasarawa State',
  'Federal University Lokoja, Kogi State',
  'Federal University Ndufu-Alike, Ebonyi State',
  'Federal University of Agriculture Abeokuta',
  'Federal University of Petroleum Resources, Effurun',
  'Federal University of Technology Akure',
  'Federal University of Technology Minna',
  'Federal University of Technology Owerri',
  'Federal University Otuoke, Bayelsa',
  'Federal University Oye-Ekiti, Ekiti State',
  'Federal University Wukari, Taraba State',
  'Michael Okpara University of Agriculture Umudike',
  'Modibbo Adama University of Technology, Yola',
  'National Open University of Nigeria',
  'Nigerian Defence Academy,Kaduna',
  'Nigeria Police Academy Wudil',
  'Nnamdi Azikiwe University, Awka',
  'Obafemi Awolowo University,Ile-Ife',
  'University of Abuja, Gwagwalada',
  'University of Agriculture Makurdi',
  'University of Benin',
  'University of Calabar',
  'University of Ibadan',
  'University of Ilorin',
  'University of Jos',
  'University of Lagos',
  'University of Maiduguri',
  'University of Nigeria Nsukka',
  'University of Port-Harcourt',
  'University of Uyo',
  'Usumanu Danfodiyo University',
  'Abia State University, Uturu',
  'Adamawa State University Mubi',
  'Adekunle Ajasin University, Akungba',
  'Akwa Ibom State University of Technology, Uyo',
  'Ambrose Alli University, Ekpoma.',
  'Anambra State University of Science & Technology, Uli',
  'Bauchi State University Gadau',
  'Benue State University Makurdi',
  'Bukar Abba Ibrahim University Damaturu',
  'Cross River State University of Science and Technology, Calabar',
  'Delta State University Abraka',
  'Ebonyi State University, Abakaliki',
  'Ekiti State University',
  'Enugu State University of Science and Technology, Enugu',
  'Gombe State Univeristy, Gombe',
  'Ibrahim Badamasi Babangida University, Lapai',
  'Ignatius Ajuru University of Education, Rumuolumeni',
  'Imo State University, Owerri',
  'Kaduna State University, Kaduna',
  'Kano University of Science and Technology, Wudil',
  'Kebbi State University, Kebbi',
  'Kogi State University Anyigba',
  'Kwara State University, Ilorin',
  'Ladoke Akintola University of Technology, Ogbomoso',
  'Lagos State University Ojo, Lagos',
  'Nasarawa State University Keffi',
  'Niger Delta Unversity, Yenagoa',
  'Northwest University Kano',
  'Olabisi Onabanjo University Ago-Iwoye',
  'Ondo State University of Science and Technology, Okitipupa',
  'Osun State University, Oshogbo',
  'Plateau State University, Bokkos',
  'Rivers State University of Science and Technology',
  'Sokoto State University, Sokoto',
  'Sule Lamido University Jigawa',
  'Tai Solarin University of Education, Ijebu-Ode',
  'Taraba State University, Jalingo',
  'Technical University,Ibadan',
  'Umaru Musa YarAdua University, Katsina',
  'University of Medical Sciences Ondo, Ondo State',
  'Yobe State University, Damaturu',
  'Achievers University, Owo',
  'Adeleke University,Ede',
  'Afe Babalola University, Ado-Ekiti – Ekiti State',
  'African University of Science & Technology, Abuja',
  'Ajayi Crowther University, Ibadan',
  'Al-Hikmah University, Ilorin',
  'American University of Nigeria, Yola',
  'Babcock University,Ilishan-Remo',
  'Baze University',
  'Bells University of Technology, Otta',
  'Benson Idahosa University,Benin City',
  'Bingham University, New Karu',
  'Bowen University, Iwo',
  'Caleb University, Lagos',
  'Caritas University, Enugu',
  'CETEP City University, Lagos',
  'Covenant University Ota',
  'Crawford University Igbesa',
  'Crescent University',
  'Elizade University, Ilara-Mokin',
  'Evangel University, Akaeze',
  'Fountain Unveristy,Oshogbo',
  'Godfrey Okoye University, Ugwuomu-Nike – Enugu State',
  'Gregory University, Uturu',
  'Igbinedion University Okada',
  'Joseph Ayo Babalola University, Ikeji-Arakeji',
  'Katsina University, Katsina',
  'Kwararafa University, Wukari',
  'Landmark University,Omu-Aran',
  'Lead City University, Ibadan',
  'Madonna University, Okija',
  'Mcpherson University, Seriki Sotayo, Ajebo',
  'Nigerian-Turkish Nile University, Abuja',
  'Novena University, Ogume',
  'Obong University, Obong Ntak',
  'Oduduwa University, Ipetumodu – Osun State',
  'Pan-African University, Lagos',
  'Paul University, Awka – Anambra State',
  'Redeemer’s University, Mowe',
  'Renaissance University,Enugu',
  'Rhema University, Obeama-Asa – Rivers State',
  'Salem University, Lokoja',
  'Samuel Adegboyega University,Ogwa',
  'Southwestern University, Oku Owa',
  'Tansian University,Umunya',
  'University of Mkar, Mkar',
  'Veritas University',
  'Wellspring University, Evbuobanosa – Edo State',
  'Wesley Univ. of Science & Tech.,Ondo',
  'Western Delta University, Oghara.',
  'Akanu Ibiam Federal Polytechnic Unwana-Afikpo, Ebonyi State.',
  'Auchi Polytechnic, Auchi Edo State',
  'Federal Polytechnic Ado-Ekiti.',
  'Federal Polytechnic Bauchi, Bauchi State.',
  'Federal Polytechnic Bida, Niger State.',
  'Federal Polytechnic Damaturu, Yobe State.',
  'Federal Polytechnic Ede, Osun State.',
  'Federal Polytechnic Idah, Kogi State.',
  'Federal Polytechnic Ilaro, Ogun State.',
  'Federal Polytechnic Kaura Namoda, Zamfara State.',
  'Federal Polytechnic Mubi, Adamawa State.',
  'Federal Polytechnic Nasarawa, Nassarawa.',
  'Federal Polytechnic Nekede Owerri, Imo State.',
  'Federal Polytechnic Offa, Kwara State.',
  'Federal Polytechnic Oko, Anambra State.',
  'Hussaini Adamu Federal Polytechnic, Kazaure, Jigawa State.',
  'Kaduna Polytechnic, Kaduna.',
  'Waziri Umaru Federal Polytechnic, B/Kebbi, Kebbi State.',
  'Yaba College of Technology, Yaba, Lagos.',
  'Federal Polytechnic Bali, Taraba State',
  'Federal Polytechnic Ekowe, Bayelsa State.',
  'Abdu Gusau Polytechnic, Talata-Mafara, Zamfara State.',
  'Abia State Polytechnic, Aba, Abia State.',
  'Abubakar Tatari Ali Polytechnic, Bauchi.',
  'Adamawa State Polytechnic, Yola.',
  'Akwa-Ibom State College of Art and Science, Numkum',
  'Akwa Ibom State Polytechnic, Ikot-Osurua',
  'Benue State Polytechnic, Ugbokolo',
  'Delta State Polytechnic, Ogharra',
  'Delta State Polytechnic, Ozoro',
  'Delta State Polytechnic, Ugwashi-Uku',
  'Edo State Institute of Management and Technology, Usen',
  'Gateway ICT Institute, Itori, Ewekoro, Ogun State.',
  'Gateway ICT Polytechnic, Igbesa, Ogun State.',
  'Gateway ICT Polytechnic, Saapade, Ogun State.',
  'Hassan Usman Katsina Polytechnic, Katsina.',
  'Imo State Polytechnic, Umuagwo',
  'Institute of Management and Technology IMT Enugu.',
  'Jigawa State Polytechnic, Dutse',
  'Kano State Polytechnic, Kano.',
  'Kogi State Polytechnic, Lokoja.',
  'Kwara State Polytechnic, Ilorin.',
  'Lagos State Polytechnic, Ikorodu.',
  'Moshood Abiola Polytechnic, Abeokuta, Ogun State.',
  'Nasarawa State Polytechnic, Lafia.',
  'Niger State Polytechnic, Zungeru.',
  'Nuhu Bamalli Polytechnic Zaria, Kaduna State.',
  'Osun State College of Technology, Esa-Oke.',
  'Osun State Polytechnic, Iree.',
  'Plateau State Polytechnic, Barkin Ladi.',
  'Ramat Polytechnic, Maiduguri, Borno State.',
  'Rivers State Polytechnic, Bori now Ken Saro Wiwa Polytechnic.',
  'Rivers State College of Arts and Science, Rumola, Port Harcourt.',
  'Rufus Giwa Polytechnic Owo, Ondo State.',
  'Sokoto State Polytechnic, Sokoto.',
  'Taraba State Polytechnic, Jalingo.',
  'The Polytechnic Ibadan, Oyo State.',
  'The Polytechnic, Ijebu Igbo',
  'Yobe State Polytechnic, Geidam.',
  'Alvan Ikoku Federal College of Education, Owerri.',
  'FCT College of Education, Zuba',
  'Federal College of Education, Akoka',
  'Federal College of Education, Asaba',
  'Federal College of education Bauchi',
  'Federal College of Education Bida',
  'Federal College of Education Eha-Amufu',
  'Federal College of Education, Iliorin',
  'Federal College of Education (Special), Oyo',
  'Federal College of Education (Technical) Gombe',
  'Federal College of Education (Technical) Gusau',
  'Federal College of Education, (Technical) Bichi',
  'Federal College of Education, Kano City',
  'Federal College of Education, Katsina',
  'Federal College of Education, Kontagora',
  'Federal College of Education Obudu',
  'Federal College of Education, Okene',
  'Federal College of Education, Omoku',
  'Federal College of Education, Ondo',
  'Federal College of Education Abeokuta',
  'Federal College of Education, pankshin',
  'Federal College of Education, Potiskum',
  'Federal College of Education Umunze',
  'Federal College of Education, Yola',
  'Federal College of Education Zaria',
  'Adeniran Ogunsanya College of Education, Ijanikin, Lagos State',
  'Adeyemi College of Education Ondo',
  'College of Education, Afaha-Nsit',
  'College of Education, Agbor',
  'College of Education, Agbor',
  'College of Education, Akwanga',
  'College of Education, Akwanga',
  'College of Education, Azare',
  'College of Education, Ekiadolor',
  'College of Education, Gindiri',
  'College of Education, Ikere Ekiti',
  'College of Education, Katsina Ala',
  'College of Education, Oro, Kwara State',
  'College of Education, Warri',
  'College of Education, Zuba',
  'Enugu State College of Education (Technical), Enugu State',
  'Isa Kaita College of Education, Katsina',
  'Michael Otedola College of Primary Education',
  'Kaduna State College of Education, Kafanchan',
  'Kano State College of Education, Kano',
  'Kwara State College of Education',
  'Nasarawa State College of Education',
  'National Teachers Institute, kaduna',
  'Niger State College of Education, Minna',
  'Nwafor Orizu College of Education',
  'Osun State College of Education, Ila-Orangun',
  'Osun State College of Education, Ilesa',
  'Oyo State College Of Education, Oyo',
  'Rivers State College of Education',
  'Sa’adatu Rimi College of Education, Kumbotso, Kano',
  'Tai Solarin University of education',
  'Taraba State College of Education, Zing'
];
